environment: development
name: ffc-ce-payment-orchestrator
namespace: ffc-ce
image: ffc-ce-payment-orchestrator
imagePullSecret:
labels: {}
deployment:
service:
  type: ClusterIP
  port: 80
container:
  port: 3002
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 60Mi
  requestCpu: 40m
  limitMemory: 120Mi
  limitCpu: 80m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  command: ["/bin/sh", "-c"]
  args: ["node index"]
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
readinessProbe:
  path: /healthy
  port: 3002
  initialDelaySeconds: 40
  periodSeconds: 10
  failureThreshold: 3
livenessProbe:
  path: /healthz
  port: 3002
  initialDelaySeconds: 40
  periodSeconds: 10
  failureThreshold: 3
