environment: development
name: ffc-ce-payment-orchestrator
namespace: ffc-ce
workstream: ffc-ce
image: ffc-ce-payment-orchestrator

testValue: Value from values.yaml

labels: {}

containerConfigMap:
  name: ffc-ce-payment-orchestrator-config-map

postgresUsername: changeme

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

container:
  port: 3002
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 40m
  limitMemory: 120Mi
  limitCpu: 80m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  command: ["/bin/sh","-c"]
  args: ["node index"]

readinessProbe:
  path: /healthy
  port: 3002
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3002
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
