version: '3.7'
services:
  ffc-ce-payment-orchestrator:
    build: .
    image: ffc-ce-payment-orchestrator
    command: npm run start:watch
    volumes:
      - ./data/:/usr/src/app/data/
      - ./server/:/usr/src/app/server/
      - ./index.js:/usr/src/app/index.js
      - ./package.json:/usr/src/app/package.json
