{{- define "ffc-ce-payment-orchestrator.container" -}}
ports:
- containerPort: {{ .Values.container.port }}
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4}}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4}}
{{- end -}}
