{{- include "ffc-helm-library.config-map" (list . "ffc-ce-payment-orchestrator.config-map") -}}
{{- define "ffc-ce-payment-orchestrator.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
{{- end -}}
