{{- include "ffc-helm-library.container-secret" (list . "ffc-ce-payment-orchestrator.container-secret") -}}
{{- define "ffc-ce-payment-orchestrator.container-secret" -}}
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | quote }}
  POSTGRES_PASSWORD2: {{ .Values.post.password | quote }}
{{- end -}}