{{- include "ffc-helm-library.deployment" (list . "ffc-ce-payment-orchestrator.deployment") -}}
{{- define "ffc-ce-payment-orchestrator.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-ce-payment-orchestrator.container") }}
{{- end -}}
