apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ffc-ce-developer-1-edit-rolebinding
  namespace: {{ .Values.namespace }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ffc-ce-developer-1
